apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::951475483652:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::951475483652:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BJTZV3G1O5UV
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T15:03:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1555"
  uid: 83ab837e-5497-49d3-a33f-21e50a475a4b
